In [26]:
import geopandas as gpd
import pandas as pd
import sqlite3

In [5]:
# importing the polygon data from the geodataframe
pasture_gdf = gpd.GeoDataFrame.from_file('../KMZs/votm/farm_simple.geojson')
pasture_gdf.head()

            name                                           geometry
0  Farm boundary  POLYGON Z ((-89.14164 42.17151 0.00000, -89.14...
1      Paddock 1  POLYGON Z ((-89.14747 42.17183 0.00000, -89.14...
2      Paddock 2  POLYGON Z ((-89.14617 42.17203 0.00000, -89.14...
3      Paddock 3  POLYGON Z ((-89.14696 42.17160 0.00000, -89.14...
4      Paddock 4  POLYGON Z ((-89.14654 42.17100 0.00000, -89.14...

In [21]:
#stepping through all the polygons computing the centroid and pulling the lat / lon into separate columns
pasture_gdf['centroid_lat'] = pasture_gdf['geometry'].centroid.x
pasture_gdf['centroid_lon'] = pasture_gdf['geometry'].centroid.y

In [23]:
pasture_gdf.head()

,name,geometry,centroid,centroid_lat,centroid_lon
0,Farm boundary,"POLYGON Z ((-89.14164 42.17151 0.00000, -89.14...",POINT (-89.14639 42.17015),-89.146393,42.170148
1,Paddock 1,"POLYGON Z ((-89.14747 42.17183 0.00000, -89.14...",POINT (-89.14683 42.17188),-89.146826,42.171881
2,Paddock 2,"POLYGON Z ((-89.14617 42.17203 0.00000, -89.14...",POINT (-89.14557 42.17161),-89.145566,42.171606
3,Paddock 3,"POLYGON Z ((-89.14696 42.17160 0.00000, -89.14...",POINT (-89.14706 42.17131),-89.147061,42.171311
4,Paddock 4,"POLYGON Z ((-89.14654 42.17100 0.00000, -89.14...",POINT (-89.14572 42.17097),-89.145720,42.170967

In [25]:
simple_df = pasture_gdf[['name', 'centroid_lat', 'centroid_lon']]
simple_df

                    name  centroid_lat  centroid_lon
0          Farm boundary    -89.146393     42.170148
1              Paddock 1    -89.146826     42.171881
2              Paddock 2    -89.145566     42.171606
3              Paddock 3    -89.147061     42.171311
4              Paddock 4    -89.145720     42.170967
5              Paddock 5    -89.147277     42.170794
6              Paddock 6    -89.145796     42.170365
7              Paddock 7    -89.147269     42.170260
8              Paddock 8    -89.145755     42.169807
9              Paddock 9    -89.147170     42.169725
10            Paddock 10    -89.145699     42.169262
11            Paddock 11    -89.147077     42.169180
12            Paddock 12    -89.145679     42.168723
13            Paddock 13    -89.147059     42.168702
14            Paddock 14    -89.145632     42.168179
15            Paddock 15    -89.147942     42.169288
16            Paddock 16    -89.149277     42.169757
17            Paddock 17    -89.148287     42.170008
18            Paddock 18    -89.148523     42.170624
19            Paddock 19    -89.149057     42.171332
20            Paddock 20    -89.148879     42.171706
21            Paddock 21    -89.148368     42.172045
22            Paddock 22    -89.149090     42.172703
23            Paddock 23    -89.148217     42.172769
24   East 18 North third    -89.142808     42.170697
25   East 18 South third    -89.144449     42.168157
26  East 18 Middle third    -89.143989     42.169460
27      votm farm padded    -89.145000     42.170000

In [32]:
conn = sqlite3.connect('../db/geometry_centroids.db')
c = conn.cursor()

In [34]:
c.execute('pragma encoding=UTF8')

In [35]:
simple_df.to_sql('centroids', conn, index=False)

In [36]:
conn.close()